#################################################################################
# Copyright (c) 2014-2020 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.
#
################################################################################

version: "3.7"

services:
  debug:
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    working_dir: "/debug"
    volumes:
      - logging-oneui-server:/debug/oneui-server
    networks:
      - fusion

# This service creates the One UI Server component to manage both zones.
#
# Note: this component can be run in either zone, so one is chosen arbitrarily

  # Fusion OneUI Server
  fusion-oneui-server:
    image: wandisco/fusion-oneui:${FUSION_ONEUI_VERSION}
    restart: unless-stopped
    networks:
      - fusion
    ports:
      - ${ONEUI_SERVER_PORT}:8081
    environment:
      - FUSION_SERVER_HOSTNAMES=${FUSION_SERVER_HOSTNAMES}
    env_file:
      - "${COMMON_ENV}"
    volumes:
      - logging-oneui-server:/var/log/fusion/
      - fusion-oneui-h2db:/h2db
      - fusion-${ZONE_A_NAME}-etc-wandisco:/fusionConfig/${ZONE_A_NAME}
      - fusion-${ZONE_B_NAME}-etc-wandisco:/fusionConfig/${ZONE_B_NAME}

volumes:
  # Named logging volume
  logging-oneui-server:

  # h2db database for UI Server
  fusion-oneui-h2db:

  fusion-${ZONE_A_NAME}-etc-wandisco:
  fusion-${ZONE_B_NAME}-etc-wandisco:

# Used for restarting ihc servers
  fusion-${ZONE_A_NAME}-restart:
  fusion-${ZONE_B_NAME}-restart:
